version: "3.0"
services:
  app:
    image: fmahmud26/spring-with-pgql-1:v22.8.8
    container_name: spring-with-pgql-1
    networks:
      - spring-pgql-1
    ports:
      - "8000:8080"
    build:
      context: .
    volumes:
      - ./spring-with-pgql-1/tmp/docker:/var/lib/docker/tmp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-1:5432/user-db
      - SPRING_DATASOURCE_USERNAME=user-name
      - SPRING_DATASOURCE_PASSWORD=user-pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    container_name: postgres-1
    networks:
      - spring-pgql-1
    ports:
      - "5431:5432"
    volumes:
      - ./spring-with-pgql-1/tmp/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=user-pass
      - POSTGRES_USER=user-name
      - POSTGRES_DB=user-db

networks:
  spring-pgql-1: